[package]
name = "leds"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cortex-m-rt = "0.7.1"
cortex-m = "0.7.4"
embedded-hal = "0.2.7"

stm32f3xx-hal = { version = "0.9.0" }